#!/bin/bash

# To archive files generated by runAnalysis.C
# Arguments: $1=task_name $2=output_dir

TASK_NAME=$1
OUTPUT_DIR=output/$2/

mkdir -p $OUTPUT_DIR
mv $1* $OUTPUT_DIR/
mv *.xml *.root $OUTPUT_DIR/
mv outputs_valid $OUTPUT_DIR
cp *.C $OUTPUT_DIR
